### ISSUE TITLE
Cannot save results from ParallelMap

### ISSUE THREAD

**Issue by atlaie** [esi-neuroscience/acme#40]
Using acme.ParallelMap and the esi-2021b kernel, I get an error when trying to write the result of a custom function to a file, but I can execute this exact same script (notebook) if I change to the previous kernel (esi-2021a). In both cases, the function is correctly computed, the only issue is with the esi-2021b kernel, when writing those results. 

My path name when it worked was: '/mnt/hpx/home/tlaieboriaa/ACME_20220208-114022-532197/score_computing_0.h5'

This is the error message:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-41-4d0913b440de> in <module>
      2     n_inputs=1)
      3 with pmap as p:
----> 4     results = p.compute()

/mnt/hpx/opt/env/python/x86_64/conda/envs/esi-2021b/lib/python3.8/site-packages/acme/backend.py in compute(self, debug)
    568                 values = []
    569                 for fname in self.kwargv["outFile"]:
--> 570                     h5Name = os.path.join(dirname, fname)
    571                     pklName = h5Name.rstrip(".h5") + ".pickle"
    572                     if os.path.isfile(h5Name):

/mnt/hpx/opt/env/python/x86_64/conda/envs/esi-2021b/lib/python3.8/posixpath.py in join(a, *p)
     74     will be discarded.  An empty last part will result in a path that
     75     ends with a separator."""
---> 76     a = os.fspath(a)
     77     sep = _get_sep(a)
     78     path = a

TypeError: expected str, bytes or os.PathLike object, not Future

**Comment by pantaray** [comment]
Hi! Thanks for reporting - this is definitely a bug introduced in the latest version of ACME. I'll look into this!

**Comment by pantaray** [comment]
Hey @atlaie ! I've started investigating the bug you reported but I'm having a hard time reproducing it. Do you maybe have a minimal example of a function where the esi-2021b kernel crashes with the above `TypeError`?

**Comment by pantaray** [comment]
Hi @atlaie ! Is this still something that causes problems for you? If not, I'd go ahead and close the issue.

**Comment by pantaray** [comment]
Hi @atlaie I'm closing this issue for now, please feel free to open a new one in case of problems.
