### ISSUE TITLE
Syncopy <ACME: ParallelMap> WARNING: Cluster node esi-svhpc2 not recognized.

### ISSUE THREAD

**Issue by timnaher** [esi-neuroscience/acme#42]
When I try to spawn parallel jobs while being on esi-svhpc2, ill get the following error:

`Syncopy <ACME: ParallelMap> WARNING: Cluster node esi-svhpc2 not recognized. Falling back to vanilla SLURM setup allocating one worker and one core per job`

the code that generated this problem is:

```
fois = np.arange(1, 90, step=1)

wav_spectra = spy.freqanalysis(adata,
method='wavelet',
foi=fois,
parallel=True,
keeptrials=True)
```

**Comment by pantaray** [comment]
Thanks for reporting!

**Comment by pantaray** [comment]
Related todo: remove mentions of HPX from docu
