### ISSUE TITLE
Error in syncopy, due to acme?

### ISSUE THREAD

**Issue by KatharineShapcott** [esi-neuroscience/acme#44]
Seems that syncopy expects acme to accept partition='auto' mem_per_job='auto' settings, should it?

https://github.com/esi-neuroscience/syncopy/issues/370#issue-1429559855

**Comment by pantaray** [comment]
Hi! See my comment over there. I'm not sure what's going on exactly. With ACME < 2022.8 the `partition="auto"` settings should just fall back to "8GBXS" on the ESI cluster.
